# Generated by Django 3.2.4 on 2022-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('CompanyId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('Abstract', models.TextField()),
                ('Price', models.DecimalField(max_digits=8, decimal_places=2)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
